---
rule_files:
- manifests/prometheus_alerts.yaml
- manifests/prometheus_rules.yaml

evaluation_interval: 1m

tests:
# Absent metrics
- interval: 1m
  input_series:
  alert_rule_test:
  - eval_time: 10m
    alertname: certmanager_absent
    exp_alerts:
    - exp_labels:
        severity: critical
        job: cert-manager
      exp_annotations:
        message: Cert Manager has dissapeared from Prometheus service discovery
        impact: New certificates will not be able to be minted, and existing ones can't be renewed until cert-manager is back.
        action: Investigate why Cert Manager has stopped running, and fix. It could also be an issue with the PodMonitor CRD.
  - eval_time: 10m
    alertname: certmanager_cert_expiry_metric_missing
    exp_alerts:
    - exp_labels:
        severity: critical
      exp_annotations:
        message: The metric used to observe cert-manager cert expiry is missing
        impact: We are blind as to whether or not we can alert on certificates expiring
        action: Assuming cert-manager is running, this is likely due to cert-manager not having permission to see certificate CRDs,
          a breaking change in metrics exposed, or some other misconfiguration.
        dashboard: https://grafana.example.com/d/TvuRo2iMk/cert-manager

# Cert expiry
- interval: 1m
  input_series:
  - series: certmanager_certificate_expiration_timestamp_seconds{exported_namespace="test", name="expired-ingress-cert", foo="bar"}
    values: 1814400+0x43200  # 21d in seconds, static for 30d of samples
  - series: certmanager_certificate_expiration_timestamp_seconds{exported_namespace="test", name="90d-ingress-cert"}
    values: 7776000+0x43200  # 90d in seconds, static for 30d of samples
  alert_rule_test:
  - eval_time: 61m
    alertname: certmanager_cert_expiry_soon
    exp_alerts:
    - exp_labels:
        severity: critical
        exported_namespace: test
        name: expired-ingress-cert
      exp_annotations:
        message: The cert `expired-ingress-cert` is 20d 22h 59m 0s from expiry, it should have renewed over a week ago
        impact: The domain that this cert covers will be unavailable after 20d 22h 59m 0s
        action: Ensure cert-manager is configured correctly, no lets-encrypt rate limits are being hit. To break glass, buy a cert.
        dashboard: https://grafana.example.com/d/TvuRo2iMk/cert-manager

# Cert not ready
- interval: 1m
  input_series:
  - series: certmanager_certificate_ready_status{exported_namespace="test", name="ready", condition="True"}
    values: 1+0x30
  - series: certmanager_certificate_ready_status{exported_namespace="test", name="not ready", condition="False"}
    values: 1+0x30
  - series: certmanager_certificate_ready_status{exported_namespace="test", name="who knows", condition="Unknown"}
    values: 1+0x30
  alert_rule_test:
  - eval_time: 10m
    alertname: certmanager_cert_not_ready
    exp_alerts:
    - exp_labels:
        severity: critical
        exported_namespace: test
        name: not ready
        condition: "False"
      exp_annotations:
        message: The cert `not ready` is not ready to serve traffic.
        impact: This certificate has not been ready to serve traffic for at least 10m. If the cert is being renewed or there is another valid cert,
          nginx _may_ be able to serve that instead.
        action: Ensure cert-manager is configured correctly, no lets-encrypt rate limits are being hit. To break glass, buy a cert.
        dashboard: https://grafana.example.com/d/TvuRo2iMk/cert-manager
    - exp_labels:
        severity: critical
        exported_namespace: test
        name: who knows
        condition: "Unknown"
      exp_annotations:
        message: The cert `who knows` is not ready to serve traffic.
        impact: This certificate has not been ready to serve traffic for at least 10m. If the cert is being renewed or there is another valid cert,
          nginx _may_ be able to serve that instead.
        action: Ensure cert-manager is configured correctly, no lets-encrypt rate limits are being hit. To break glass, buy a cert.
        dashboard: https://grafana.example.com/d/TvuRo2iMk/cert-manager

# cert-manager rate limits
- interval: 1m
  input_series:
  - series: certmanager_http_acme_client_request_count{status="200", host="normal.acme-v02.api.letsencrypt.org", path="/acme/new-order"}
    values: 1+1x30
  - series: certmanager_http_acme_client_request_count{status="429", host="rate-limited.acme-v02.api.letsencrypt.org", path="/acme/new-order"}
    values: 1+1x30
  - series: certmanager_http_acme_client_request_count{status="429", host="one-limited-request.acme-v02.api.letsencrypt.org", path="/acme/new-order"}
    values: 1+0x30
  alert_rule_test:
  - eval_time: 10m
    alertname: certmanager_hitting_rate_limits
    exp_alerts:
    - exp_labels:
        severity: critical
        host: rate-limited.acme-v02.api.letsencrypt.org
      exp_annotations:
        message: Cert manager hitting LetsEncrypt rate limits
        impact: Depending on the rate limit, cert-manager may be unable to generate certificates for up to a week.
        action: Nothing we can really do in the short term. We can apply for a rate limit adjustment for the future,
          but it can take weeks to approve. Thoughts and prayers.
        dashboard: https://grafana.example.com/d/TvuRo2iMk/cert-manager
        link_url: https://docs.google.com/forms/d/e/1FAIpQLSetFLqcyPrnnrom2Kw802ZjukDVex67dOM2g4O8jEbfWFs3dA/viewform
        link_text: LetsEncrypt Rate Limit Request Form
